USE master
GO

IF DB_ID('BDSECRETARIAIDES') IS NOT NULL
BEGIN
    ALTER DATABASE BDSECRETARIAIDES SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE BDSECRETARIAIDES
END
GO

CREATE DATABASE BDSECRETARIAIDES
GO

USE BDSECRETARIAIDES
GO

CREATE TABLE ALUNO (
    CODALUNO INT IDENTITY(1,1) NOT NULL,
    NOMEALUNO VARCHAR(50) NOT NULL,
    RG CHAR(15) NOT NULL,
    EMISSAO CHAR(2) NOT NULL,
    DATANASC DATE NOT NULL,
    CPF CHAR(14) NULL,
    FILIACAOMAE VARCHAR(50) NULL,
    FILIACAOPAI VARCHAR(50) NULL,
    CEP CHAR(9) NULL,
    ENDERECO VARCHAR(50) NULL,
    NUMERO CHAR(6) NULL,
    COMPLEMENTO VARCHAR(20) NULL,
    BAIRRO VARCHAR(50) NULL,
    CIDADE VARCHAR(50) NULL,
    ESTADO CHAR(2) NULL,
    TIPOTEL1 VARCHAR(15) NOT NULL,
    TELEFONE1 CHAR(14) NOT NULL,
    OBSERVACAOTEL1 VARCHAR(20) NULL,
    TIPOTEL2 VARCHAR(15) NULL,
    TELEFONE2 CHAR(14) NULL,
    OBSERVACAOTEL2 VARCHAR(20) NULL,
    TIPOTEL3 VARCHAR(15) NULL,
    TELEFONE3 CHAR(14) NULL,
    OBSERVACAOTEL3 VARCHAR(20) NULL,
    EMAIL VARCHAR(50) NULL,
    CONSTRAINT PK_ALUNO PRIMARY KEY (CODALUNO)
)
GO

CREATE TABLE CURSO (
    CODCURSO INT IDENTITY(1,1) NOT NULL,
    NOMECURSO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY (CODCURSO)
)
GO

CREATE TABLE PROFESSOR (
    CODPROFESSOR INT IDENTITY(1,1) NOT NULL,
    NOMEPROFESSOR VARCHAR(50) NOT NULL,
    RG CHAR(15) NOT NULL,
    EMISSAO CHAR(2) NOT NULL,
    DATANASC DATE NOT NULL,
    CPF CHAR(14) NOT NULL,
    FILIACAOMAE VARCHAR(50) NULL,
    FILIACAOPAI VARCHAR(50) NULL,
    CEP CHAR(9) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    NUMERO CHAR(6) NOT NULL,
    COMPLEMENTO VARCHAR(50) NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    TIPOTEL1 VARCHAR(15) NOT NULL,
    TELEFONE1 CHAR(14) NOT NULL,
    OBSERVACAOTEL1 VARCHAR(20) NULL,
    TIPOTEL2 VARCHAR(15) NULL,
    TELEFONE2 CHAR(14) NULL,
    OBSERVACAOTEL2 VARCHAR(20) NULL,
    TIPOTEL3 VARCHAR(15) NULL,
    TELEFONE3 CHAR(14) NULL,
    OBSERVACAOTEL3 VARCHAR(20) NULL,
    EMAIL VARCHAR(50) NULL,
    ESCOLARIDADE VARCHAR(50) NOT NULL,
    DTADMISSAO DATE NOT NULL,
    DTDEMISSAO DATE NULL,
    CONSTRAINT PK_PROFESSOR PRIMARY KEY (CODPROFESSOR)
)
GO

CREATE TABLE USUARIO (
    CODUSUARIO INT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    SOBRENOME VARCHAR(30) NOT NULL,
    CPF CHAR(14) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    EMAIL VARCHAR(50) NULL,
    NOMEUSUARIO VARCHAR(30) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    ACESSO VARCHAR(20) NOT NULL,
    FOTO VARBINARY(MAX) NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (CODUSUARIO)
)
GO

CREATE TABLE TURMA (
    CODTURMA INT IDENTITY(1,1) NOT NULL,
    QTDVAGAS CHAR(3) NOT NULL,
    DIASEMANA VARCHAR(20) NOT NULL,
    HORAENTRADA TIME NOT NULL,
    HORASAIDA TIME NOT NULL,
    DATAINICIO DATE NOT NULL,
    DATACONCLUSAO DATE NOT NULL,
    CODPROFESSOR INT NOT NULL,
    CODCURSO INT NOT NULL,
    CONSTRAINT PK_TURMA PRIMARY KEY (CODTURMA),
    CONSTRAINT FK_TURMA_PROFESSOR FOREIGN KEY (CODPROFESSOR)
        REFERENCES PROFESSOR (CODPROFESSOR),
    CONSTRAINT FK_TURMA_CURSO FOREIGN KEY (CODCURSO)
        REFERENCES CURSO (CODCURSO)
)
GO

CREATE TABLE MATRICULA (
    CODMATRICULA INT IDENTITY(1,1) NOT NULL,
    MATRICULANUMERO VARCHAR(20) NOT NULL,
    DATAMATRICULA DATE NOT NULL,
    CODALUNO INT NOT NULL,
    CODTURMA INT NOT NULL,
    CODUSUARIO INT NOT NULL,
    CONSTRAINT PK_MATRICULA PRIMARY KEY (CODMATRICULA),
    CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY (CODALUNO)
        REFERENCES ALUNO (CODALUNO),
    CONSTRAINT FK_MATRICULA_TURMA FOREIGN KEY (CODTURMA)
        REFERENCES TURMA (CODTURMA),
    CONSTRAINT FK_MATRICULA_USUARIO FOREIGN KEY (CODUSUARIO)
        REFERENCES USUARIO (CODUSUARIO)
)
GO